version: 2.1

jobs:
  build:
    docker:
      - image: node:14

    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

  test:
    docker:
      - image: node:14

    steps:
      - checkout
      - run: npm ci
      - run: npm run test

  analyze:
    docker:
      - image: node:14

    steps:
      - checkout
      - run: npm ci
      - run: npm audit

workflows:
  version: 2
  build_test_analyze:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
